### ISSUE TITLE
Possibly wrong implementation of "format_units"

### ISSUE THREAD

**Issue by paulrberg** [gakonst/ethers-rs#168]
## Description

I was looking to use the [format-units](https://docs.rs/ethers-core/0.2.0/ethers_core/utils/fn.format_units.html) function, part of `ethers-core::utils`. I was expecting the same [behaviour](https://docs.ethers.io/v5/api/utils/display-logic/#utils-formatUnits) as in the canonical ethers.js, but the `format_units` function behaves differently in ethers-rs.

## Actual Behaviour
Take the following Rust code:

```rust
use ethers::{prelude::*, utils::format_units};
let eth_in_wei = U256::from_dec_str("1000000000000000000").unwrap();
let eth_in_gwei = format_units(eth_in_wei, 9);
println!("eth_in_gwei: {:?}", eth_in_gwei);
```

This logs the following:

```rust
eth_in_gwei: 111111111111111111
```

## Expected Behaviour

Take the following JavaScript code:

```javascript
const { ethers } = require("ethers");
let eth_in_wei = "1000000000000000000";
const eth_in_gwei = ethers.utils.formatUnits(eth_in_wei, 9);
console.log({ eth_in_gwei });
```

This logs the following:

```javascript
{ eth_in_gwei: '1000000000.0' }
```

Which is correct, as per the identity 1 eth = 1e9 gwei = 1e18 wei.

## Possible Solution

Rewrite the [format_units](https://github.com/gakonst/ethers-rs/blob/0.2.0/ethers-core/src/utils/mod.rs#L42-L44) function to divide by `10^(decimals)` instead of just `decimals`.

## Environment
Using ethers-rs@0.2.0

**Comment by gakonst** [comment]
This should be fixed in #170 @paulrberg!

**Comment by sakulstra** [comment]
hey just doing my first steps with rust and I think there might still be an issue:
```
// js
ethers.utils.formatUnits("409030851937682650000",18) ->  "409.03085193768265"

// ethers-rs
format_units(&U256::from_dec_str("409030851937682650000"), 18).to_string(); -> "409"
```

**Comment by x3ccd4828** [comment]
@gakonst can you reopen this issue since it's still not correct?

**Comment by gakonst** [comment]
i think this was addressed in https://github.com/gakonst/ethers-rs/pull/463?

**Comment by x3ccd4828** [comment]
I have modified the parse_unit test to show that if you have 18 decimal places some are lost since f64 doesn't have enough bits to hold such a high precision number. 

https://github.com/x3ccd4828/ethers-rs/commit/617997a41d736ab93a18e6bb461656eeb61769dc

**Comment by x3ccd4828** [comment]
I can submit a pull request with a fix but it will have to use the rug crate (https://crates.io/crates/rug) to create a float larger than 64bit.

**Comment by x3ccd4828** [comment]
@gakonst have you had a chance to look at the modified test?

**Comment by gakonst** [comment]
+1 on the test and using `rug` with `default-features = false`
