### ISSUE TITLE
WS Event Stream may hang if provider closes

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#391]
**Version**

All versions w/ websocket support

**Description**

From Nathan Barnavon:

I'm trying to listen to events while connected to a provider. The problem I am running into is I cannot seem to detect when the connection with a provider has closed, and so I will wait forever. Any suggestions on how I should detect if the provider has closed the stream?

Example
```
async fn stream_event_loop(client: EvmClient, contract: AnchorContract<Provider<Ws>>) -> Result<(), anyhow::Error> {
    let current_block_number = client.provider.get_block_number().await.unwrap();
    let events_filter = contract.deposit_filter().from_block(current_block_number);
    let events = events_filter.subscribe().await?;
    let mut stream = events.with_meta();

    while let Some(v) = stream.try_next().map_err(Error::from).await? {
        let (_e, log) = v;
        println!("Got new Event at block {}", log.block_number);
    }
    Ok(())
}
```

**Proposed Solution**
1. Partially fixed in #387 so that the the outer stream ends when the internal stream ends
2. AFAIK there's no way to detect if the other side of the websocket connection is closed. The only way for us to do that would be to add a periodic Ping message and return an error in the internal filter watcher.

**Comment by mattsse** [comment]
I guess this happens because we actually never do anything if the underlying websocket was closed in the spawned server
https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/transports/ws.rs#L213
since the websocket is unusable after that, should we close the and drop all channels, ergo closing alls subscriptions?

**Comment by gakonst** [comment]
Fixed in #396.

**Comment by vinceniko** [comment]
This issue still appears for me on master when subscribing to an abi autogenerated event filter.

### example
Using the abi auto generated filter doesn't work:
```{rust}
let filter = contract.event_filter();
let mut event_stream = filter.subscribe().await?;

let event: Event = event_stream
    .next()
    .await
    .ok_or("failed")??
```

Manually subscribing to the filter works correctly, i.e. an Err Result variant is returned when the ws connection is dropped:
```{rust}
let filter = contract.event_filter();
let mut event_stream = client.subscribe_logs(&filter.filter).await?;

let event: Event = filter.parse_log(
    event_stream
        .next()
        .await
        .ok_or("failed")?,
)?;
```
