### ISSUE TITLE
Windows build failure with features = ["ws", "rustls"]

### ISSUE THREAD

**Issue by jacobkaufmann** [gakonst/ethers-rs#598]
**Version**

```shell
ethers-rs-windows v0.1.0 (C:\Users\jacob\Workspace\ethers-rs-windows)
├── ethers-providers v0.5.5
│   ├── ethers-core v0.5.5
```
**Platform**

```shell
$ rustc --print=cfg
debug_assertions
target_arch="x86_64"
target_endian="little"
target_env="msvc"
target_family="windows"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_os="windows"
target_pointer_width="64"
target_vendor="pc"
windows

```

**Description**

It seems that there is some code that should be specific to the `ipc` feature that is not properly scoped with the `cfg` attribute. We would like to use `ethers-rs` in our multi-platform project, but it failed the Windows build CI task. I was able to reproduce it with the minimal code given below.

As far as I can tell, my `Cargo.toml` is configured correctly, but it's possible I made a simple mistake there.

I tried this code:

`src/main.rs`
```rust
use ethers_providers::{Provider, Http, Middleware};
use std::convert::TryFrom;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let provider = Provider::<Http>::try_from(
        "https://mainnet.infura.io/v3/c5ec4bd6f66f42558f5fae017c1032ff"
    )?;
    
    let block = provider.get_block(100u64).await?;
    println!("Got block: {}", serde_json::to_string(&block)?);
    Ok(())
}
```

`Cargo.toml`
```toml
[dependencies]
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[target.'cfg(unix)'.dependencies]
ethers-providers = { version = "0.5.5" }

[target.'cfg(windows)'.dependencies]
ethers-providers = { version="0.5.5", default-features = false, features = ["ws", "rustls"] }
```

I expected to see this happen: Run and print block 100.

Instead, this happened: Build failure.

```shell
$ cargo build
   Compiling ethers-providers v0.5.5
error[E0432]: unresolved import `tokio::net::UnixStream`
  --> C:\Users\jacob\.cargo\registry\src\github.com-1ecc6299db9ec823\ethers-providers-0.5.5\src\transports\ipc.rs:22:5
   |
22 |     net::UnixStream,
   |     ^^^^^^^^^^^^^^^ no `UnixStream` in `net`

error[E0599]: no function or associated item named `connect` found for struct `ipc::Ipc` in the current scope
   --> C:\Users\jacob\.cargo\registry\src\github.com-1ecc6299db9ec823\ethers-providers-0.5.5\src\provider.rs:919:31
    |
919 |         let ipc = crate::Ipc::connect(path).await?;
    |                               ^^^^^^^ function or associated item not found in `ipc::Ipc`
    |
   ::: C:\Users\jacob\.cargo\registry\src\github.com-1ecc6299db9ec823\ethers-providers-0.5.5\src\transports\ipc.rs:30:1
    |
30  | pub struct Ipc {
    | -------------- function or associated item `connect` not found for this
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `connect`, perhaps you need to implement one of them:
            candidate #1: `hyper::client::connect::sealed::Connect`
            candidate #2: `hyper::client::connect::sealed::ConnectSvc`

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `ethers-providers` due to 2 previous errors
```

**Comment by mattsse** [comment]
hmm, I believe this was fixed, can you try with `master` instead of crates.io?

**Comment by jacobkaufmann** [comment]
Tried with `git = "https://github.com/gakonst/ethers-rs"`, still seeing same failure.

**Comment by jacobkaufmann** [comment]
Seems to be resolved with dependency version bump to `0.6.0`. I took some time to try to identify the relevant change, but that effort has not been successful. Closing.
